### PR TITLE
Update test.js

### PR DESCRIPTION
**Pull request by ghost**
**Me** and _Bill Gates_ looked at this and we added a comment, # Juju # might remove it because she might think I did it by myself. But I made _Bill Gates_ talk to _her mum_ on the phone for 3 minutes. I'm a better programmer.

### CODE REVIEW

**Comment by ghost** [comment]
Bill Gates does not speak french

**Review by Legend-of-iPhoenix — APPROVED** [review]
Clearly adds to the program without inducing bugs, should be merged ASAP.

**Comment by juju2143** [comment]
what the hell guys

**Comment by ghost** [comment]
Why not

**Review by ghost — COMMENTED** [review]
get the other stuff out

**Comment by ghost** [comment]
bill gates looks like quagmire and cannot speak

**Comment by ghost** [comment]
Why not

**Comment by ghost** [comment]
juju is not wanting any jobs at microsoft any more

**Comment by ghost** [comment]
come on think of 5 ideas for programs

**Pull request closed without merging**
